unit Terraria.ChunkGenerator;

{$mode objfpc}{$H+}

{ TChunkGenerator — procedural terrain + vegetation + cave decorations.

  GENERATION PIPELINE PER CHUNK
  ──────────────────────────────
  1. GenerateColumn        – solid tiles (terrain + biome depth zones)
  2. FillBackgroundColumn  – wall tiles behind air
  3. PlaceGrassColumn      – topmost dirt → grass (only at the true surface row)
  4. PlantVegetation       – trees, shrubs, cacti on the surface
  5. PlaceCaveDecor        – roots/vines (ceiling), stalactites/stalagmites,
                             mushrooms (floor), moss patches

  FIX NOTES
  ─────────
  • PlaceGrassColumn: now verifies that the first non-air tile found in the
    local chunk column is actually the global surface row (TY = ASurface).
    Chunks entirely below the surface no longer convert their topmost dirt
    tile to grass.

  • PlantVegetationForColumn: guards that the local surface LY, when
    converted to a world Y, matches the stored surface for that column.
    Also passes the world X (TX) and chunk Y origin to PlantTree /
    PlantCactus so cross-chunk tiles are written via FManager.SetFG.

  • PlantTree / PlantCactus: cross-chunk canopy and body tiles are written
    through FManager.SetFG (world tile coordinates) instead of SafeSetFG,
    so tiles that fall outside the current chunk are placed correctly in
    the neighbouring chunk.

  • PlantShrub: added check that the surface tile is TILE_DIRT or TILE_GRASS
    before placing the shrub, preventing shrubs from appearing on tree
    trunks/leaves or other surface objects.

  • SetFGWorld: new helper that converts a world tile coordinate pair to the
    correct chunk + local coordinate and delegates to FManager, handling
    cross-chunk writes safely. }

interface

uses
   SysUtils, Math,
   Terraria.Common,
   Terraria.WorldChunk,
   Terraria.ChunkManager,
   Terraria.Noise,
   Terraria.GenParams;

type
   TChunkGenerator = class
   private
      FSeed: longint;
      FParams: TGenParams;
      FManager: TChunkManager;

      { Terrain }
      function ComputeSurfaceY(TX: Integer): Integer;
      function ComputeBiome(TX: Integer): byte;
      function ForegroundTile(TX, TY, ASurface: Integer; ABiome: byte): byte;
      function IsCaveAt(TX, TY: Integer; ACaveMult: Single): boolean;
      procedure GenerateColumn(AChunk: TWorldChunk; LX, ACX, ACY: Integer);
      { PlaceGrassColumn now requires the world Y of the surface for the
        column so it can validate the tile before converting it. }
      procedure PlaceGrassColumn(AChunk: TWorldChunk; LX, ACY, ASurface: Integer);
      procedure FillBackgroundColumn(AChunk: TWorldChunk; LX, ACX, ACY, ASurface: Integer; ABiome: byte);

      { Vegetation — TX and OriginTY carry world coordinates so that
        cross-chunk tiles can be written via SetFGWorld. }
      procedure PlantTree(AChunk: TWorldChunk; LX, SurfLY, TX, OriginTY: Integer; const V: TVegetationParams);
      procedure PlantShrub(AChunk: TWorldChunk; LX, SurfLY: Integer);
      procedure PlantCactus(AChunk: TWorldChunk; LX, SurfLY, TX, OriginTY: Integer; const V: TVegetationParams);
      procedure PlantVegetationForColumn(AChunk: TWorldChunk; LX, ACX, ACY: Integer);

      { Cave decorations }
      procedure PlaceCaveDecor(AChunk: TWorldChunk; LX, ACX, ACY: Integer);

      { Shared helpers }
      function SurfaceLocalY(AChunk: TWorldChunk; LX: Integer): Integer;
      function TileIsAir(AChunk: TWorldChunk; LX, LY: Integer): boolean; inline;
      function TileIsSolid(AChunk: TWorldChunk; LX, LY: Integer): boolean; inline;
      function TileIsDirt(AChunk: TWorldChunk; LX, LY: Integer): boolean; inline;
      function TileIsStone(AChunk: TWorldChunk; LX, LY: Integer): boolean; inline;
      { Safe set — clamps to chunk bounds, does nothing if LY out of range }
      procedure SafeSetFG(AChunk: TWorldChunk; LX, LY: Integer; ATile: byte);
      { Cross-chunk safe set — writes to ANY world tile coordinate through
        FManager, creating the target chunk on demand if needed. }
      procedure SetFGWorld(WX, WY: Integer; ATile: byte);
   public
      constructor Create(AManager: TChunkManager; ASeed: longint);
      procedure GenerateChunk(ACX, ACY: Integer; AChunk: TWorldChunk);
      procedure ApplyParams;
      property Seed: longint read FSeed write FSeed;
      property Params: TGenParams read FParams write FParams;
   end;

implementation

uses
   P2D.Utils.Logger;

{ ---------------------------------------------------------------------------
  Helper: SetFGWorld
  Writes ATile to world-tile position (WX, WY).  The call is forwarded to
  FManager which converts world → chunk → local coords and creates the
  target chunk if it does not yet exist (triggering generation for that
  chunk, which is safe because chunk (ACX, ACY) is already present in the
  hash table and will not be re-generated by the recursive call).
  Coordinates outside the vertical world bounds are silently ignored.
--------------------------------------------------------------------------- }
procedure TChunkGenerator.SetFGWorld(WX, WY: Integer; ATile: byte);
var
   CY: Integer;
begin
   { Respect vertical world limits }
   CY := TChunkManager.TileToChunkY(WY);
   if (CY < WORLD_MIN_CY) or (CY > WORLD_MAX_CY) then
      Exit;
   FManager.SetFG(WX, WY, ATile);
end;

{ ---------------------------------------------------------------------------
  Terrain helpers (unchanged)
--------------------------------------------------------------------------- }

function TChunkGenerator.TileIsAir(AChunk: TWorldChunk; LX, LY: Integer): boolean;
begin
   Result := AChunk.InLocalBounds(LX, LY) and (AChunk.GetFG(LX, LY) = TILE_AIR);
end;

function TChunkGenerator.TileIsSolid(AChunk: TWorldChunk; LX, LY: Integer): boolean;
var
   T: byte;
begin
   if not AChunk.InLocalBounds(LX, LY) then
   begin
      Result := True;
      Exit;
   end;
   T := AChunk.GetFG(LX, LY);
   Result := (T <> TILE_AIR) and (T < TILE_SHRUB);
end;

function TChunkGenerator.TileIsDirt(AChunk: TWorldChunk; LX, LY: Integer): boolean;
var
   T: byte;
begin
   if not AChunk.InLocalBounds(LX, LY) then
   begin
      Result := False;
      Exit;
   end;
   T := AChunk.GetFG(LX, LY);
   Result := (T = TILE_DIRT) or (T = TILE_GRASS) or (T = TILE_CLAY) or (T = TILE_GRAVEL);
end;

function TChunkGenerator.TileIsStone(AChunk: TWorldChunk; LX, LY: Integer): boolean;
var
   T: byte;
begin
   if not AChunk.InLocalBounds(LX, LY) then
   begin
      Result := False;
      Exit;
   end;
   T := AChunk.GetFG(LX, LY);
   Result := (T = TILE_STONE) or (T = TILE_GRANITE) or (T = TILE_MARBLE) or (T = TILE_SANDSTONE) or (T = TILE_BEDROCK);
end;

function TChunkGenerator.SurfaceLocalY(AChunk: TWorldChunk; LX: Integer): Integer;
var
   LY: Integer;
begin
   Result := -1;
   for LY := 0 to CHUNK_TILES_H - 1 do
      if AChunk.GetFG(LX, LY) <> TILE_AIR then
      begin
         Result := LY;
         Exit;
      end;
end;

procedure TChunkGenerator.SafeSetFG(AChunk: TWorldChunk; LX, LY: Integer; ATile: byte);
begin
   if AChunk.InLocalBounds(LX, LY) then
      AChunk.SetFG(LX, LY, ATile);
end;

{ ---------------------------------------------------------------------------
  constructor / ApplyParams / ComputeSurfaceY / ComputeBiome (unchanged)
--------------------------------------------------------------------------- }

constructor TChunkGenerator.Create(AManager: TChunkManager; ASeed: longint);
begin
   inherited Create;
   FManager := AManager;
   FSeed := ASeed;
   FParams := DefaultGenParams;
   FParams.Seed := ASeed;
end;

procedure TChunkGenerator.ApplyParams;
begin
   ClampGenParams(FParams);
   FSeed := FParams.Seed;
end;

function TChunkGenerator.ComputeSurfaceY(TX: Integer): Integer;
var
   N: Single;
   Biome: byte;
   BP: TBiomeParams;
begin
   N := FBM1D(TX * FParams.SurfaceFreq, FParams.SurfaceOctaves, FParams.SurfaceLacun, FParams.SurfaceGain);
   Biome := ComputeBiome(TX);
   case Biome of
      BIOME_DESERT:
         BP := FParams.BiomeDesert;
      BIOME_FOREST:
         BP := FParams.BiomeForest;
      else
         BP := FParams.BiomePlains;
   end;
   Result := FParams.BaseSurface + BP.SurfaceOffsetY + Round(N * (FParams.SurfaceAmp + BP.SurfaceAmpBonus));
   Result := Max(FParams.MinSurface, Min(FParams.MaxSurface, Result));
end;

function TChunkGenerator.ComputeBiome(TX: Integer): byte;
var
   N: Single;
begin
   N := (FBM1D(TX * FParams.BiomeFreq + 900, FParams.BiomeOctaves) + 1.0) * 0.5;
   if N < FParams.DesertThreshold then
      Result := BIOME_DESERT
   else
   if N < FParams.ForestThreshold then
      Result := BIOME_PLAINS
   else
      Result := BIOME_FOREST;
end;

{ ---------------------------------------------------------------------------
  ForegroundTile (unchanged)
--------------------------------------------------------------------------- }

function TChunkGenerator.ForegroundTile(TX, TY, ASurface: Integer; ABiome: byte): byte;
var
   Depth: Integer;
   N: Single;
   BP: TBiomeParams;
   EffDirt, EffDirtStone, EffSandstone: Integer;
   EffGranThr, EffMarbThr, EffClayThr, EffGravThr: Single;
begin
   if TY < ASurface then
   begin
      Result := TILE_AIR;
      Exit;
   end;
   Depth := TY - ASurface;
   case ABiome of
      BIOME_DESERT:
         BP := FParams.BiomeDesert;
      BIOME_FOREST:
         BP := FParams.BiomeForest;
      else
         BP := FParams.BiomePlains;
   end;
   EffDirt := IfThen(BP.DepthDirtOverride > 0, BP.DepthDirtOverride, FParams.DepthDirt);
   EffDirtStone := IfThen(BP.DepthDirtStoneOverride > 0, BP.DepthDirtStoneOverride, FParams.DepthDirtStone);
   EffSandstone := IfThen(BP.SandstoneDepth > 0, BP.SandstoneDepth, FParams.SandstoneExtra);
   EffGranThr := IfThen(BP.GraniteThreshold > 0, BP.GraniteThreshold, FParams.GraniteThreshold);
   EffMarbThr := IfThen(BP.MarbleThreshold > 0, BP.MarbleThreshold, FParams.MarbleThreshold);
   EffClayThr := IfThen(BP.ClayThreshold > 0, BP.ClayThreshold, FParams.ClayThreshold);
   EffGravThr := IfThen(BP.GravelThreshold > 0, BP.GravelThreshold, FParams.GravelThreshold);

   if Depth = 0 then
   begin
      if BP.SurfaceTileOverride > 0 then
      begin
         Result := BP.SurfaceTileOverride;
         Exit;
      end;
      if ABiome = BIOME_DESERT then
         Result := TILE_SAND
      else
         Result := TILE_DIRT;
      Exit;
   end;
   if Depth <= EffDirt then
   begin
      if ABiome = BIOME_DESERT then
         Result := TILE_SAND
      else
         Result := TILE_DIRT;
      Exit;
   end;
   if (ABiome = BIOME_DESERT) and (Depth <= EffDirt + EffSandstone) then
   begin
      Result := TILE_SANDSTONE;
      Exit;
   end;
   if Depth <= EffDirtStone then
   begin
      N := ValueNoise2D(TX * 0.18, TY * 0.18);
      if N > (0.4 - Depth * 0.02) then
         Result := TILE_STONE
      else
         Result := TILE_DIRT;
      if (N > EffClayThr) and (Depth < EffDirtStone - 2) then
         Result := TILE_CLAY;
      N := ValueNoise2D(TX * 0.22 + 50, TY * 0.22 + 50);
      if N > EffGravThr then
         Result := TILE_GRAVEL;
      Exit;
   end;
   if Depth <= FParams.DepthStone then
   begin
      Result := TILE_STONE;
      N := FBM2D(TX * FParams.GraniteFreq, TY * FParams.GraniteFreq, 2);
      if N > EffGranThr then
         Result := TILE_GRANITE;
      N := FBM2D(TX * FParams.MarbleFreq + 200, TY * FParams.MarbleFreq + 200, 2);
      if N > EffMarbThr then
         Result := TILE_MARBLE;
      Exit;
   end;
   N := ValueNoise2D(TX * 0.07, TY * 0.07);
   if N > FParams.DeepGraniteRatio then
      Result := TILE_MARBLE
   else
      Result := TILE_GRANITE;
   if TY >= TChunkManager.ChunkToTileY(WORLD_MAX_CY + 1) - FParams.BedrockRows then
      Result := TILE_BEDROCK;
end;

function TChunkGenerator.IsCaveAt(TX, TY: Integer; ACaveMult: Single): boolean;
var
   N, EffThreshold: Single;
begin
   if ACaveMult <= 0 then
   begin
      Result := False;
      Exit;
   end;
   N := FBM2D(TX * FParams.CaveFreqX, TY * FParams.CaveFreqY, FParams.CaveOctaves);
   EffThreshold := Min(0.49, FParams.CaveThreshold * ACaveMult);
   Result := Abs(N) < EffThreshold;
end;

{ ---------------------------------------------------------------------------
  GenerateColumn (unchanged)
--------------------------------------------------------------------------- }

procedure TChunkGenerator.GenerateColumn(AChunk: TWorldChunk; LX, ACX, ACY: Integer);
var
   TX, TY, WY, SY: Integer;
   Biome: byte;
   TileVal: byte;
   CaveMult: Single;
   BP: TBiomeParams;
begin
   TX := TChunkManager.ChunkToTileX(ACX) + LX;
   SY := ComputeSurfaceY(TX);
   Biome := ComputeBiome(TX);
   FManager.SetSurfaceY(TX, SY);
   FManager.SetBiome(TX, Biome);
   case Biome of
      BIOME_DESERT:
         BP := FParams.BiomeDesert;
      BIOME_FOREST:
         BP := FParams.BiomeForest;
      else
         BP := FParams.BiomePlains;
   end;
   CaveMult := BP.CaveDensityMult;
   for WY := 0 to CHUNK_TILES_H - 1 do
   begin
      TY := TChunkManager.ChunkToTileY(ACY) + WY;
      TileVal := ForegroundTile(TX, TY, SY, Biome);
      if FParams.CavesEnabled and (TileVal <> TILE_AIR) and (TileVal <> TILE_BEDROCK) and (TY >= SY + FParams.CaveStartDepth) then
         if IsCaveAt(TX, TY, CaveMult) then
            TileVal := TILE_AIR;
      AChunk.SetFG(LX, WY, TileVal);
   end;
end;

{ ---------------------------------------------------------------------------
  FillBackgroundColumn (unchanged)
--------------------------------------------------------------------------- }

procedure TChunkGenerator.FillBackgroundColumn(AChunk: TWorldChunk; LX, ACX, ACY, ASurface: Integer; ABiome: byte);
var
   WY, TY, Depth: Integer;
   WallTile: byte;
   BP: TBiomeParams;
   EffDirt, EffDirtStone: Integer;
begin
   case ABiome of
      BIOME_DESERT:
         BP := FParams.BiomeDesert;
      BIOME_FOREST:
         BP := FParams.BiomeForest;
      else
         BP := FParams.BiomePlains;
   end;
   EffDirt := IfThen(BP.DepthDirtOverride > 0, BP.DepthDirtOverride, FParams.DepthDirt);
   EffDirtStone := IfThen(BP.DepthDirtStoneOverride > 0, BP.DepthDirtStoneOverride, FParams.DepthDirtStone);
   for WY := 0 to CHUNK_TILES_H - 1 do
   begin
      TY := TChunkManager.ChunkToTileY(ACY) + WY;
      Depth := TY - ASurface;
      if TY < ASurface then
      begin
         AChunk.SetBG(LX, WY, TILE_AIR);
         Continue;
      end;
      if Depth <= EffDirt then
         if ABiome = BIOME_DESERT then
            WallTile := TILE_SAND
         else
            WallTile := TILE_DIRT
      else
      if Depth <= EffDirtStone then
         WallTile := TILE_DIRT
      else
         WallTile := TILE_STONE;
      if TY >= TChunkManager.ChunkToTileY(WORLD_MAX_CY + 1) - FParams.BedrockRows then
         WallTile := TILE_BEDROCK;
      AChunk.SetBG(LX, WY, WallTile);
   end;
end;

{ ---------------------------------------------------------------------------
  FIX 1 — PlaceGrassColumn
  ─────────────────────────
  The original version simply converted the first non-air tile in the local
  chunk column to grass.  For chunks that are entirely below the surface
  chunk (e.g., the player has dug down to chunk CY=2 while the surface is
  in CY=1), the topmost tile at LY=0 is underground dirt — and it was
  incorrectly turned into grass.

  Fix: compute the world Y (TY) of the first non-air local tile and compare
  it against the stored per-column surface Y (ASurface).  Grass is only
  placed when TY == ASurface, i.e., when this tile really is the surface.
--------------------------------------------------------------------------- }

procedure TChunkGenerator.PlaceGrassColumn(AChunk: TWorldChunk; LX, ACY, ASurface: Integer);
var
   LY, TY: Integer;
   ChunkOriginTY: Integer;
begin
   ChunkOriginTY := TChunkManager.ChunkToTileY(ACY);
   for LY := 0 to CHUNK_TILES_H - 1 do
   begin
      if AChunk.GetFG(LX, LY) <> TILE_AIR then
      begin
         TY := ChunkOriginTY + LY;
         { Only convert to grass when this tile IS the global surface row }
         if (TY = ASurface) and (AChunk.GetFG(LX, LY) = TILE_DIRT) then
            AChunk.SetFG(LX, LY, TILE_GRASS);
         Break;
      end;
   end;
end;

{ ---------------------------------------------------------------------------
  FIX 1+3 — PlantVegetationForColumn
  ────────────────────────────────────
  FIX 1:  Guard added at the top — if the local surface LY, when converted
          to a world Y, does not equal the stored surface for this column,
          the column is entirely below (or entirely above) the surface and
          we must not plant anything.  This prevents underground tiles from
          being decorated as if they were on the surface.

  FIX 3:  The shrub placement check now also verifies that the tile AT
          SurfLY is TILE_GRASS or TILE_DIRT.  This prevents shrubs from
          being placed on top of tree trunks/leaves (which can appear at
          SurfLY when a tree trunk has been detected as the topmost
          non-air tile by SurfaceLocalY).
--------------------------------------------------------------------------- }

procedure TChunkGenerator.PlantVegetationForColumn(AChunk: TWorldChunk; LX, ACX, ACY: Integer);
var
   TX: Integer;
   Biome: byte;
   V: TVegetationParams;
   SLY: Integer;
   TY, OriginTY: Integer;
   N: Single;
   Lc: Integer;
   CanPlace: boolean;
   SurfTile: byte;
begin
   TX := TChunkManager.ChunkToTileX(ACX) + LX;
   OriginTY := TChunkManager.ChunkToTileY(ACY);
   Biome := FManager.GetBiome(TX);

   case Biome of
      BIOME_DESERT:
         V := FParams.VegDesert;
      BIOME_FOREST:
         V := FParams.VegForest;
      else
         V := FParams.VegPlains;
   end;

   SLY := SurfaceLocalY(AChunk, LX);
   if SLY < 0 then
      Exit;   { entire column is air }

   { FIX 1: verify this is really the global surface row }
   TY := OriginTY + SLY;
   if TY <> FManager.GetSurfaceY(TX) then
      Exit;   { surface is in a different chunk — nothing to plant here }

   { Trees need at least one row of sky above them inside this chunk }
   if SLY = 0 then
      Exit;

   { ── Trees ── }
   if V.TreeEnabled then
   begin
      N := (ValueNoise1D(TX * V.TreeNoiseFreq + FSeed * 0.001) + 1.0) * 0.5;
      if N < V.TreeNoiseThresh then
      begin
         CanPlace := True;
         for Lc := Max(0, LX - 2) to Min(CHUNK_TILES_W - 1, LX + 2) do
            if (Lc <> LX) and (AChunk.GetFG(Lc, SLY - 1) in [TILE_TREE_TRUNK, TILE_CACTUS]) then
            begin
               CanPlace := False;
               Break;
            end;
         if CanPlace then
            PlantTree(AChunk, LX, SLY, TX, OriginTY, V);
      end;
   end;

   { ── Shrubs / ferns ──
     FIX 3: only place on actual ground tiles (TILE_DIRT or TILE_GRASS).
     This stops shrubs from spawning on top of tree trunks/leaves. }
   if V.ShrubEnabled and TileIsAir(AChunk, LX, SLY - 1) then
   begin
      SurfTile := AChunk.GetFG(LX, SLY);
      if (SurfTile = TILE_GRASS) or (SurfTile = TILE_DIRT) or (SurfTile = TILE_SAND) then
      begin
         N := (ValueNoise1D(TX * V.ShrubNoiseFreq + FSeed * 0.007 + 333) + 1.0) * 0.5;
         if N < V.ShrubNoiseThresh then
            PlantShrub(AChunk, LX, SLY);
      end;
   end;

   { ── Cacti ── }
   if V.CactusEnabled and TileIsAir(AChunk, LX, SLY - 1) then
   begin
      N := (ValueNoise1D(TX * V.CactusNoiseFreq + FSeed * 0.003 + 777) + 1.0) * 0.5;
      if N < V.CactusNoiseThresh then
         PlantCactus(AChunk, LX, SLY, TX, OriginTY, V);
   end;
end;

{ ---------------------------------------------------------------------------
  FIX 2 — PlantTree
  ─────────────────
  Cross-chunk canopy tiles now use SetFGWorld(WX, WY, tile) instead of
  SafeSetFG(LX2, LY2, tile).  SetFGWorld converts local offsets to world
  coordinates and delegates to FManager, which creates the neighbouring
  chunk on demand (without re-generating the current one).

  The trunk itself stays within the current chunk via SafeSetFG because the
  surface is guaranteed to be inside this chunk (guarded in
  PlantVegetationForColumn).  The canopy is what can overflow horizontally
  and/or vertically.
--------------------------------------------------------------------------- }

procedure TChunkGenerator.PlantTree(AChunk: TWorldChunk; LX, SurfLY, TX, OriginTY: Integer; const V: TVegetationParams);
{ FIX — vertical chunk crossing for trunk:
  TrunkH is no longer clamped to fit inside the current chunk.
  Both trunk and canopy are placed in world coordinates; tiles that land
  outside the current chunk are written through SetFGWorld (which calls
  FManager.SetFG and creates the neighbour chunk on demand). }
var
   TrunkH, R, H, DX, DY: Integer;
   TrunkBottomWY, TrunkTopWY, WY: Integer;
   CanopyWX, CanopyWY: Integer;
   LocalX, LocalY: Integer;
begin
   if SurfLY <= 0 then
      Exit;
   if not TileIsAir(AChunk, LX, SurfLY - 1) then
      Exit;

   { Trunk height from noise — NOT clamped to chunk boundary }
   TrunkH := V.TreeMinHeight + (Abs(Round(ValueNoise1D(LX * 7.3 + FSeed * 0.01) * 100)) mod Max(1, V.TreeMaxHeight - V.TreeMinHeight + 1));
   TrunkH := Max(V.TreeMinHeight, Min(V.TreeMaxHeight, TrunkH));

   { World Y of the bottom-most trunk tile (just above the surface tile) }
   TrunkBottomWY := OriginTY + SurfLY - 1;
   { World Y of the top-most trunk tile }
   TrunkTopWY := TrunkBottomWY - TrunkH;
   { Clamp to the world's topmost row }
   if TrunkTopWY < TChunkManager.ChunkToTileY(WORLD_MIN_CY) then
      TrunkTopWY := TChunkManager.ChunkToTileY(WORLD_MIN_CY);

   { Place trunk tiles in world coordinates.
     Tiles that fall inside the current chunk use the fast local path;
     tiles in the chunk above are placed via SetFGWorld. }
   for WY := TrunkTopWY to TrunkBottomWY do
   begin
      LocalX := LX;
      LocalY := WY - OriginTY;
      if AChunk.InLocalBounds(LocalX, LocalY) then
         AChunk.SetFG(LocalX, LocalY, TILE_TREE_TRUNK)
      else
         SetFGWorld(TX, WY, TILE_TREE_TRUNK);
   end;

   { Canopy — oval centred on the trunk top in world coordinates }
   R := V.TreeCanopyRadius;
   H := V.TreeCanopyHeight;

   for DY := -H to H do
      for DX := -R to R do
      begin
         if (DX * DX * H * H + DY * DY * R * R) > (R * R * H * H) then
            Continue;

         CanopyWX := TX + DX;
         CanopyWY := TrunkTopWY + DY;

         LocalX := CanopyWX - TX + LX;
         LocalY := CanopyWY - OriginTY;
         if AChunk.InLocalBounds(LocalX, LocalY) then
         begin
            if TileIsAir(AChunk, LocalX, LocalY) then
               AChunk.SetFG(LocalX, LocalY, TILE_TREE_LEAF);
         end
         else
            SetFGWorld(CanopyWX, CanopyWY, TILE_TREE_LEAF);
      end;
end;

{ ---------------------------------------------------------------------------
  PlantShrub (unchanged except it is now called only after the ground-tile
  check in PlantVegetationForColumn — FIX 3)
--------------------------------------------------------------------------- }

procedure TChunkGenerator.PlantShrub(AChunk: TWorldChunk; LX, SurfLY: Integer);
begin
   if SurfLY <= 0 then
      Exit;
   if not TileIsAir(AChunk, LX, SurfLY - 1) then
      Exit;
   SafeSetFG(AChunk, LX, SurfLY - 1, TILE_SHRUB);
end;

{ ---------------------------------------------------------------------------
  FIX 2 — PlantCactus
  ────────────────────
  Cactus body and arm tiles use SetFGWorld for positions that may fall
  outside the current chunk boundaries.
--------------------------------------------------------------------------- }

procedure TChunkGenerator.PlantCactus(AChunk: TWorldChunk; LX, SurfLY, TX, OriginTY: Integer; const V: TVegetationParams);
var
   CactH, LY, MidY, ArmY, TopY: Integer;
   GrowLeft: boolean;
   NArmChance: Single;
   WYbase: Integer;
begin
   if SurfLY <= 1 then
      Exit;
   if not TileIsAir(AChunk, LX, SurfLY - 1) then
      Exit;

   CactH := V.CactusMinHeight + (Abs(Round(ValueNoise1D(LX * 11.7 + FSeed * 0.02) * 100)) mod Max(1, V.CactusMaxHeight - V.CactusMinHeight + 1));
   CactH := Max(V.CactusMinHeight, Min(V.CactusMaxHeight, CactH));

   { Body — grows upward; write local tiles where possible, cross-chunk via manager }
   for LY := SurfLY - 1 downto Max(0, SurfLY - CactH) do
      SafeSetFG(AChunk, LX, LY, TILE_CACTUS);

   { Arm — can overflow one tile horizontally }
   if V.CactusArmChance > 0 then
   begin
      NArmChance := (ValueNoise1D(LX * 3.3 + FSeed * 0.03) + 1.0) * 0.5;
      if NArmChance < V.CactusArmChance then
      begin
         MidY := SurfLY - 1 - CactH div 2;
         if MidY >= 0 then
         begin
            GrowLeft := ValueNoise1D(LX * 17.1 + FSeed) > 0;
            ArmY := MidY;
            WYbase := OriginTY + ArmY;
            if GrowLeft then
            begin
               SetFGWorld(TX - 1, WYbase, TILE_CACTUS);
               SetFGWorld(TX - 1, WYbase - 1, TILE_CACTUS_TOP);
            end
            else
            begin
               SetFGWorld(TX + 1, WYbase, TILE_CACTUS);
               SetFGWorld(TX + 1, WYbase - 1, TILE_CACTUS_TOP);
            end;
         end;
      end;
   end;

   { Top cap }
   TopY := Max(0, SurfLY - CactH);
   SafeSetFG(AChunk, LX, TopY, TILE_CACTUS_TOP);
end;

{ ---------------------------------------------------------------------------
  PlaceCaveDecor (unchanged)
--------------------------------------------------------------------------- }

procedure TChunkGenerator.PlaceCaveDecor(AChunk: TWorldChunk; LX, ACX, ACY: Integer);
var
   LY, TX, TY, Len, I: Integer;
   CD: TCaveDecoParams;
   N: Single;
   SurfTY: Integer;
   Biome: byte;
   DepthBelowSurf: Integer;
begin
   CD := FParams.CaveDecor;
   TX := TChunkManager.ChunkToTileX(ACX) + LX;
   SurfTY := FManager.GetSurfaceY(TX);
   Biome := FManager.GetBiome(TX);

   for LY := 1 to CHUNK_TILES_H - 2 do
   begin
      TY := TChunkManager.ChunkToTileY(ACY) + LY;
      DepthBelowSurf := TY - SurfTY;
      if DepthBelowSurf < FParams.CaveStartDepth then
         Continue;
      if not TileIsAir(AChunk, LX, LY) then
         Continue;

      if TileIsSolid(AChunk, LX, LY - 1) then
      begin
         if CD.RootsEnabled and TileIsDirt(AChunk, LX, LY - 1) then
         begin
            N := (ValueNoise1D(TX * CD.RootsNoiseFreq + LY * 2.3 + FSeed * 0.02) + 1.0) * 0.5;
            if N < CD.RootsDensity then
            begin
               Len := CD.RootsMinLen + Abs(Round(N * 100)) mod Max(1, CD.RootsMaxLen - CD.RootsMinLen + 1);
               for I := 0 to Len - 1 do
                  if TileIsAir(AChunk, LX, LY + I) then
                     SafeSetFG(AChunk, LX, LY + I, TILE_ROOT)
                  else
                     Break;
            end;
         end;
         if CD.VinesEnabled and TileIsStone(AChunk, LX, LY - 1) and (DepthBelowSurf > FParams.DepthDirt + 4) then
         begin
            N := (ValueNoise1D(TX * CD.VinesNoiseFreq + LY * 3.1 + FSeed * 0.04 + 500) + 1.0) * 0.5;
            if N < CD.VinesDensity then
            begin
               Len := CD.VinesMinLen + Abs(Round(N * 100)) mod Max(1, CD.VinesMaxLen - CD.VinesMinLen + 1);
               for I := 0 to Len - 1 do
                  if TileIsAir(AChunk, LX, LY + I) then
                     SafeSetFG(AChunk, LX, LY + I, TILE_VINE)
                  else
                     Break;
            end;
         end;
         if CD.StalEnabled and TileIsStone(AChunk, LX, LY - 1) then
         begin
            N := (ValueNoise1D(TX * CD.StalNoiseFreq + LY * 5.7 + FSeed * 0.05 + 1000) + 1.0) * 0.5;
            if N < CD.StalDensity then
            begin
               Len := CD.StalMinLen + Abs(Round(N * 100)) mod Max(1, CD.StalMaxLen - CD.StalMinLen + 1);
               for I := 0 to Len - 1 do
                  if TileIsAir(AChunk, LX, LY + I) then
                     SafeSetFG(AChunk, LX, LY + I, TILE_STALACTITE)
                  else
                     Break;
            end;
         end;
         if CD.MossEnabled and TileIsStone(AChunk, LX, LY - 1) then
         begin
            N := (ValueNoise1D(TX * CD.MossNoiseFreq + LY * 1.9 + FSeed * 0.03 + 2000) + 1.0) * 0.5;
            if N < CD.MossDensity then
               SafeSetFG(AChunk, LX, LY, TILE_MOSS);
         end;
      end;

      if TileIsSolid(AChunk, LX, LY + 1) then
      begin
         if CD.StalEnabled and TileIsStone(AChunk, LX, LY + 1) then
         begin
            N := (ValueNoise1D(TX * CD.StalNoiseFreq + LY * 4.4 + FSeed * 0.06 + 3000) + 1.0) * 0.5;
            if N < (CD.StalDensity * 0.6) then
            begin
               Len := CD.StalMinLen + Abs(Round(N * 100)) mod Max(1, CD.StalMaxLen - CD.StalMinLen + 1);
               for I := 0 to Len - 1 do
                  if TileIsAir(AChunk, LX, LY - I) then
                     SafeSetFG(AChunk, LX, LY - I, TILE_STALAGMITE)
                  else
                     Break;
            end;
         end;
         if CD.MushEnabled and (DepthBelowSurf >= CD.MushMinDepth) and TileIsAir(AChunk, LX, LY - 1) then
         begin
            N := (ValueNoise1D(TX * 0.9 + LY * 6.2 + FSeed * 0.07 + 4000) + 1.0) * 0.5;
            if N < CD.MushDensity then
               SafeSetFG(AChunk, LX, LY, TILE_MUSHROOM);
         end;
      end;
   end;
end;

{ ---------------------------------------------------------------------------
  GenerateChunk — updated Pass 3 call signature
--------------------------------------------------------------------------- }

procedure TChunkGenerator.GenerateChunk(ACX, ACY: Integer; AChunk: TWorldChunk);
var
   LX, TX, SY: Integer;
   Biome: byte;
begin
   NoiseSeed(FSeed);

   { Pass 1: solid tiles }
   for LX := 0 to CHUNK_TILES_W - 1 do
      GenerateColumn(AChunk, LX, ACX, ACY);

   { Pass 2: background walls }
   for LX := 0 to CHUNK_TILES_W - 1 do
   begin
      TX := TChunkManager.ChunkToTileX(ACX) + LX;
      SY := FManager.GetSurfaceY(TX);
      Biome := FManager.GetBiome(TX);
      FillBackgroundColumn(AChunk, LX, ACX, ACY, SY, Biome);
   end;

   { Pass 3: grass on topmost dirt — now passes ACY and per-column surface Y
     so the surface-row guard works correctly across chunk boundaries }
   for LX := 0 to CHUNK_TILES_W - 1 do
   begin
      TX := TChunkManager.ChunkToTileX(ACX) + LX;
      SY := FManager.GetSurfaceY(TX);
      PlaceGrassColumn(AChunk, LX, ACY, SY);
   end;

   { Pass 4: surface vegetation }
   for LX := 0 to CHUNK_TILES_W - 1 do
      PlantVegetationForColumn(AChunk, LX, ACX, ACY);

   { Pass 5: cave decorations }
   if FParams.CavesEnabled then
      for LX := 0 to CHUNK_TILES_W - 1 do
         PlaceCaveDecor(AChunk, LX, ACX, ACY);
end;

end.
